[[tls.certificates]]
  certFile = "/ssl/twake-server-fullchain.pem"
  keyFile  = "/ssl/twake-server.key"
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/ssl/twake-server-fullchain.pem"
      keyFile = "/ssl/twake-server.key"


[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    sniStrict = false
    

[http.serversTransports]
  [http.serversTransports.insecure-transport]
    insecureSkipVerify = true    
