mongo.url=mongodb://mongo:27017
mongo.database=esn_docker
domains=twake.local
rest.api.port=80
spa.calendar.url=https://calendar.twake.local/calendar/
spa.excal.url=https://excal.twake.local

jwt.key.private=file:///root/conf/jwt_privatekey
jwt.key.public=file:///root/conf/jwt_publickey

oidc.issuer.url=https://auth.twake.local/
oidc.userInfo.url=https://auth.twake.local/oauth2/userinfo
oidc.introspect.url=https://auth.twake.local/oauth2/introspect
oidc.introspect.credentials=Basic b3BlbnBhYXM6b3BlbnBhYXM=
oidc.claim=email
oidc.introspection.claim=email
oidc.audience=openpaas



calendar.sharing.enabled=true
contacts.sharing.enabled=true
domain.contacts.enabled=true
default.language=en
default.timezone=Europe/Paris
default.business.hours.start=8:0
default.business.hours.end=19:0
default.business.hours.daysOfWeek=1,2,3,4,5,6
default.use.24h.format=true

dav.url=https://sabre-dav.twake.local
dav.admin.user=admin
dav.admin.password=secret123
dav.rest.client.response.timeout=120000
dav.rest.client.trust.all.ssl.certs=true

smtp.host=smtp-server.local
smtp.port=25
smtp.helo=smtp-server.local
smtp.ssl.enabled=false
smtp.ssl.trustAllCerts=false
smtp.starttls.enabled=false

mail.template.location=file://root/resources/templates
mail.sender=no-reply@twake.local
mail.imip.recipient.whitelist=alice@twake.local,bob@twake.local,cedric@twake.local,admin@twake.local

admin.username=admin@twake.local
admin.password=admin

self.url=https://tcalendar-side-service.twake.local
default.calendar.public.visibility.enabled=true
