opensearch.hosts=opensearch:9200
opensearch.clusterName=opensearch
opensearch.hostScheme=http

opensearch.nb.shards=5
opensearch.nb.replica=0
opensearch.retryConnection.maxRetries=7
opensearch.retryConnection.minDelay=3000
