enabled=true
port=8000
host=0.0.0.0

https.enabled=false

webadmin.cors.enabled=true
webadmin.cors.origins=https://calendar.twake.local
webadmin.cors.methods=GET,POST,PUT,DELETE,OPTIONS
webadmin.cors.headers=Authorization,Content-Type
