version: '3.8'

include:
  - drive_app/docker-compose.yml
  - visio_app/docker-compose.yml
  - linshare_app/docker-compose.yml
  - twake_db/docker-compose.yml
  - twake_auth/docker-compose.yml
  - token_manager/docker-compose.yml