services:
  tcalendar-frontend:
    image: linagora/twake-calendar-web:branch-master
    container_name: twake_calendar_frontend
    networks:
      - twake-network
    ports:
      - "3000:80"
    volumes:
      - ./frontend/env.js:/usr/share/nginx/html/.env.js

  tcalendar-side-service:
    image: linagora/twake-calendar-side-service:branch-master
    container_name: tcalendar-side-service.twake.local
    hostname: tcalendar-side-service.twake.local
    networks:
      - twake-network
    volumes:
      - ./conf-side-service:/root/conf
      - ./root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt:ro
      #- ./entrypoint.sh:/entrypoint.sh:ro
    extra_hosts:
      - "sabre-dav.linagora.local:172.27.0.5"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sidesvc.rule=Host(`tcalendar-side-service.twake.local`)"
      - "traefik.http.routers.sidesvc.entrypoints=websecure"
      - "traefik.http.routers.sidesvc.middlewares=cors"
      - "traefik.http.services.sidesvc.loadbalancer.server.port=80"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://calendar.twake.local,https://contacts.twake.local,https://account.twake.local,https://excal.twake.local"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=Authorization,Content-Type"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"  
      
  fe-calendar:
    image: linagora/esn-frontend-calendar:govmu-02
    hostname: calendar.twake.local
    environment:
      - OPENPAAS_URL=https://tcalendar-side-service.twake.local
    volumes:
      - ./frontend/calendar/openpaas.js:/usr/share/nginx/html/assets/env/openpaas.js
    networks:
      - twake-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fecalendar.rule=Host(`calendar.twake.local`)" 
      - "traefik.http.services.fecalendar.loadbalancer.server.port=80"
      
  fe-excal:
    image: linagora/esn-frontend-calendar-public:main
    hostname: excal.twake.local
    environment:
      - OPENPAAS_URL=https://tcalendar-side-service.twake.local
    volumes:
      - ./frontend/calendar/openpaas.js:/usr/share/nginx/html/assets/env/openpaas.js
    networks:
      - twake-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feexcal.rule=Host(`excal.twake.local`)" 
      - "traefik.http.services.feexcal.loadbalancer.server.port=80"

  fe-contacts:
    image: linagora/esn-frontend-contacts:17-01-2025
    hostname: contacts.twake.local
    environment:
      - OPENPAAS_URL=https://tcalendar-side-service.twake.local
    volumes:
      - ./frontend/contacts/openpaas.js:/usr/share/nginx/html/assets/env/openpaas.js
    networks:
      - twake-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fecontacts.rule=Host(`contacts.twake.local`)" 
      - "traefik.http.services.fecontacts.loadbalancer.server.port=80"
      
  fe-account:
    image: linagora/esn-frontend-account:main
    hostname: account.twake.local
    environment:
      - OPENPAAS_URL=https://tcalendar-side-service.twake.local
    volumes:
      - ./frontend/account/openpaas.js:/usr/share/nginx/html/assets/env/openpaas.js
    networks:
      - twake-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feaccount.rule=Host(`account.twake.local`)" 
      - "traefik.http.services.feaccount.loadbalancer.server.port=80"

  sabre_dav:
    image: linagora/esn-sabre:sabre-4_7_0-09-01-2026
    container_name: sabre_dav
    hostname: sabre-dav.twake.local
    networks:
      - twake-network
    environment:
      - SABRE_ENV=dev
      - SABRE_MONGO_HOST=mongodb
      - SABRE_MONGO_PORT=27017
      - ESN_MONGO_HOST=mongodb
      - ESN_MONGO_PORT=27017
      - ESN_MONGO_DBNAME=esn_docker
      - ESN_HOST=tcalendar-side-service.twake.local
      - ESN_PORT=80
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_LOGIN=tcalendar
      - AMQP_PASSWORD=tcalendar
      - SABRE_ADMIN_LOGIN=admin
      - SABRE_ADMIN_PASSWORD=secret123
      - SABRE_IMPERSONATION_ENABLED=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabredav.rule=Host(`sabre-dav.twake.local`)"  
      - "traefik.http.services.sabredav.loadbalancer.server.port=80"  
    volumes:
      - ./conf-side-service/jwt_publickey:/var/www/config/esn.key.pub



networks:
  twake-network:
    external: true
