services:
  n8n:
    image: n8n-patched:latest
    container_name: n8n
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6120:5678"
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
    external: true
