services:

  cozy-stack:
    image: cozy/cozy-stack:latest
    container_name: cozyt
    restart: unless-stopped
   
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cozy.rule=HostRegexp(`{subdomain:user3-home|user3|user3-drive|user3-linshare|user3-mail|user3-settings|oauthcallback|user1|user1-home|user1-linshare|user1-settings|user1-drive|user1-mail|user2|user2-home|user2-settings|user2-linshare|user2-mail|user2-drive}.twake.local`)"
      - "traefik.http.routers.cozy.entrypoints=websecure"
      - "traefik.http.routers.cozy.tls=true"
      - "traefik.http.services.cozy.loadbalancer.server.port=8080"
    environment:
      COUCHDB_HOST: couchdb
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
      COZY_ADMIN_PASSPHRASE: admin
      INBOX_SECRET: secret
      OUTBOX_SECRET: secret
    extra_hosts:
      - "auth.twake.local:172.27.0.100"
      - "user1.twake.local:172.27.0.100"
      - "user2.twake.local:172.27.0.100"
      - "user3.twake.local:172.27.0.100"
    volumes:
      - /cozy-data:/var/lib/cozy/
      - ./config/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./config/cozy.yaml:/etc/cozy/cozy.yaml
      - ./config/root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt
      - ./config/create-shortcut.sh:/usr/local/bin/create-shortcut.sh
      - ./config/change-features.sh:/usr/local/bin/change-features.sh
      - ./config/example-features.json:/usr/local/bin/example-features.json
      - ./config/example-shortcut.json:/usr/local/bin/example-shortcut.json
    networks:
      - twake-network  
  patcher-cozy:
    image: docker:26-cli
    container_name: patcher-cozy
    networks:
      - twake-network

    depends_on:
      - cozy-stack  
    environment:
      - CONTAINER=cozyt   
    volumes:
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh", "/scripts/entrypoint.sh"]
    restart: "no" 
volumes:
  cozy-data:    
networks:
  twake-network:
    external: true
