services:
  onlyoffice-documentserver:
    #build:
      #context: .
    image: onlyoffice/documentserver:8.0.1 #[-de,-ee]
    container_name: onlyoffice-documentserver

    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - DB_PWD=onlyoffice
      - AMQP_URI=amqp://guest:guest@rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      - JWT_ENABLED=true
      - JWT_SECRET=secret
      - USE_UNAUTHORIZED_STORAGE=true
      - USE_FORWARDED_HEADERS=true
      - ALLOW_META_IP_ADDRESS=true
      - ALLOW_PRIVATE_IP_ADDRESS=true
      - SSL_CERTIFICATE_PATH=/var/www/onlyoffice/Data/certs/root-ca.pem
      - SSL_KEY_PATH=/var/www/onlyoffice/Data/certs/root-ca.key
      #- JWT_HEADER=Authorization
      #- JWT_IN_BODY=true
    #ports:
      #- '80:80'
      #- '443:443'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.twake.local`)"
      - "traefik.http.routers.onlyoffice.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice.tls=true"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=443" 
      - "traefik.http.services.onlyoffice.loadbalancer.server.scheme=https"
      - "traefik.http.services.onlyoffice.loadbalancer.serversTransport=insecure-transport@file" 
      #- "traefik.enable=true"
      #- "traefik.http.routers.onlyoffice-http.rule=Host(`onlyoffice.twake.local`)"
      #- "traefik.http.routers.onlyoffice-http.entrypoints=web"
      #- "traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.twake.local`)"
      #- "traefik.http.routers.onlyoffice.entrypoints=websecure"
      #- "traefik.http.routers.onlyoffice-http.middlewares=redirect-to-https"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info/info.json"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - /var/www/onlyoffice/Data
       - /var/log/onlyoffice
       - /var/lib/onlyoffice/documentserver/App_Data/cache/files
       - /var/www/onlyoffice/documentserver-example/public/files
       - /usr/share/fonts
       - ./root-ca.pem:/var/www/onlyoffice/Data/certs/root-ca.pem
       - ./root-ca.key:/var/www/onlyoffice/Data/certs/root-ca.key
       #- ./local-production-linux.json:/etc/onlyoffice/documentserver/default.json
    extra_hosts:
       - "user1.twake.local:172.27.0.100"
       - "user2.twake.local:172.27.0.100"
       - "user3.twake.local:172.27.0.100"  
    networks:
      - twake-network   
       
        
  
networks:
  twake-network:
    external: true
volumes:
  postgresql_data: