FROM node:20-alpine AS builder
WORKDIR /app
COPY frontend-cozy/package*.json ./
RUN npm install --legacy-peer-deps
COPY frontend-cozy/ ./
RUN npm run build

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/build /app
