# Those properties let you configure the number of messages queried at the same time.
# IMAP FETCH command
fetch.metadata=1000
fetch.headers=30
fetch.body=2
fetch.full=2

# IMAP COPY command
# See https://github.com/apache/james-project/pull/2265
copy=2000000000
# IMAP MOVE command
move=2000000000

