# Configuration file for Periodical Health Checks

# Read https://james.apache.org/server/config-healthcheck.html for further details

# Optional. Period between two PeriodicalHealthChecks.
# Units supported are (ms - millisecond, s - second, m - minute, h - hour, d - day). Default unit is millisecond.
# Default duration is 60 seconds.
# Duration must be greater or at least equals to 10 seconds.
# healthcheck.period=60s

# Map of task name to its required execution duration.
# The delimiter between map entries is "," while between the mapping is ":".
# Default to empty map (no check/always healthy).
# healthcheck.tasks.execution=TaskAName:2day,TaskBName:2month,taskCName:2week

