#  This template file can be used as example for James Server configuration
#  DO NOT USE IT AS SUCH AND ADAPT IT TO YOUR NEEDS

# Read https://james.apache.org/server/config-system.html#jmx.properties for further details

jmx.enabled=true
jmx.address=127.0.0.1
jmx.port=9999
