# ============================================= Extra JVM System Properties ===========================================
# To avoid clutter on the command line, any properties in this file will be added as system properties on server start.

# Example: If you need an option -Dmy.property=whatever, you can instead add it here as
# my.property=whatever

# Required to locate Cassandra driver configuration
config.file=/root/conf/cassandra-driver.conf

james.protocols.mdc.hostname=false
james.lifecycle.leak.detection.mode=simple
james.jmap.default.charset=ISO-8859-1

james.mime4j.buffer.recycling.enabled=false

reactor.schedulers.defaultBoundedElasticSize=200

sun.rmi.dgc.server.gcInterval=3600000000
sun.rmi.dgc.client.gcInterval=3600000000

james.relaxed.mailbox.name.validation=true

# Proxy disabled for LAB environment
# com.google.api.client.should_use_proxy=false

james.s3.minio.compatibility.mode=true

tmail.eventbus.synchronous.listener.groups=PopulateEmailQueryViewListenerGroup,MailboxChangeListenerGroup
james.jmap.email.set.range.threshold=1
