# Twake sync mobile app
mobileApps.Twake_Sync.appName=Twake Sync
mobileApps.Twake_Sync.logoURL=https://github.com/linagora/twake-sync/blob/release-ose/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
mobileApps.Twake_Sync.androidPackageId=com.twake.android.sync
