opensearch.hosts=opensearch:9200
opensearch.clusterName=opensearch

# Authentication disabled for LAB environment (security plugin disabled)
# opensearch.user=admin
# opensearch.password=nM3pQ6rS9tU2vW5xY
opensearch.hostScheme=http
# opensearch.hostScheme.https.sslValidationStrategy=ignore
# opensearch.hostScheme.https.hostNameVerifier=accept_any_hostname

opensearch.nb.shards=5
opensearch.nb.replica=0
opensearch.retryConnection.maxRetries=7
opensearch.retryConnection.minDelay=3000

# Index name section
opensearch.index.mailbox.name=tmail
opensearch.alias.read.mailbox.name=tmail-read
opensearch.alias.write.mailbox.name=tmail-write
opensearch.index.quota.ratio.name=tmail-quota-ratio
opensearch.alias.read.quota.ratio.name=tmail-quota-ratio-read
opensearch.alias.write.quota.ratio.name=tmail-quota-ratio-write


opensearch.search.overrides=org.apache.james.mailbox.cassandra.search.AllSearchOverride,org.apache.james.mailbox.cassandra.search.DeletedSearchOverride, org.apache.james.mailbox.cassandra.search.DeletedWithRangeSearchOverride,org.apache.james.mailbox.cassandra.search.NotDeletedWithRangeSearchOverride,org.apache.james.mailbox.cassandra.search.UidSearchOverride,org.apache.james.mailbox.cassandra.search.UnseenSearchOverride

opensearch.indexHeaders=false
opensearch.message.index.optimize.move=true
