# OpenPaaS disabled for LAB environment
# rabbitmq.uri=amqp://tmail:pQ6rS8tU1vW4xY7zA@rabbitmq:5672
# openpaas.api.uri=http://esn:8080/api
# openpaas.admin.user=admin@poc.lin-saas.com
# openpaas.admin.password=9jZanFFNcFS7J
